# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Helénica Analítica
tagline:          'boutique software development firm'
description:      'we keep it simple'
url:              http://helenicaanalitica.site
baseurl:          /

author:
  name:           'Nestor R Benavidez'
  url:            https://nestorbenavidez.site

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
